### ISSUE TITLE
Feature request: check memId is already init and setString override options

### ISSUE THREAD

**Issue by hwen** [zhangyuang/sharedMemory#1]
Hi，thank you for your great job with this great package and save my life!

Cause there is no way to check a memId is already init，it will block the program while you init twice or use a memId before init.

So, it is necessary to provide an api to check:

1. check memId is init or not
2. possible override content while setString

**Comment by zhangyuang** [comment]
check shareMemory area has been inited is easy，what do you want when setString in old memId？override it or throw an error？



发自我的iPhone


------------------ Original ------------------
From: hwencc ***@***.***&gt;
Date: Tue, Sep 10, 2024 9:42 AM
To: zhangyuang/memoryshare ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [zhangyuang/memoryshare] Feature request: check memId is already initand setString override options (Issue #1)

**Comment by hwen** [comment]
1.

**Comment by hwen** [comment]
I use this package to dev Electron app with JS.

Cureently，I dont know a way to check init. Can you provide some suggestion to check shareMemory area with js？ Thank you!

I use this package to set a video frame in mem, so It is great that setString can override content, because we only need the latest video frame data.

**Comment by zhangyuang** [comment]
when you init a shareMemory block，the memory file will be created in disk，you can check whether the file is exist or i can provide a feature to check whether it's exist or not at next version



发自我的iPhone


------------------ Original ------------------
From: hwencc ***@***.***&gt;
Date: Tue, Sep 10, 2024 9:58 AM
To: zhangyuang/memoryshare ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/memoryshare] Feature request: check memId is alreadyinit and setString override options (Issue #1)





 
I use this package to dev Electron app with JS.
 
Cureently，I dont know a way to check init. Can you provide some suggestion to check shareMemory area with js？ Thank you!
 
I use this package to set a video frame in mem, so It is great that setString can override content, because we only need the latest video frame data.

**Comment by hwen** [comment]
Maybe a new feature is better? checking with rust is more efficiency than js

**Comment by zhangyuang** [comment]
i will support it as soon as possible



发自我的iPhone


------------------ Original ------------------
From: hwencc ***@***.***&gt;
Date: Tue, Sep 10, 2024 10:12 AM
To: zhangyuang/memoryshare ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zhangyuang/memoryshare] Feature request: check memId is alreadyinit and setString override options (Issue #1)





 
Maybe a new feature is better? checking with rust is more efficiency than js

**Comment by hwen** [comment]
Is there a way to override setString content?

Here is my code:

```js
const mshare = require('memoryshare')

mshare.clear(uid)
mshare.init(uid, maxSize)
mshare.setString(uid, str)
```

We must clear and reinit a memId, when I set a new video frame data. 

It will impact performance cause clear and reinit will del and recreate file ?

**Comment by zhangyuang** [comment]
After the test, if you create the same memId twice, it will throw an error. You can guide whether the memId has been created by capturing the error. and then, you can call setString with old memId without clearing and init it, the store data will be overridden automatically

**Comment by hwen** [comment]
it is ok! thank you
